name: PHP to HTML conversion
  
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      deployments: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Git
        run: |
          git config --global user.name "forestDean"
          git config --global user.email "email@johnwalton.uk"

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Build HTML files
        run: |
          php build.php # Replace with your PHP to HTML conversion script
       
      - name: Commit HTML files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional. Commit message for the created commit.
          commit_message: PHP to HTML conversion
          # Optional. Disable dirty check and always try to create a commit and push
          # skip_dirty_check: true     
